// Generates supabase/seed.sql from the curated seed in src/data/prompts.js.
// Run from the project root:  node supabase/generate-seed.mjs
//
// Keeps the seed SQL in sync with the canonical JS seed without hand-escaping
// multi-line prompt bodies. Uses dollar-quoting for text so quotes/newlines in
// prompt content need no escaping.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { prompts } from "../src/data/prompts.js";

const here = dirname(fileURLToPath(import.meta.url));

// Dollar-quote a string with a tag guaranteed not to appear inside it.
function dq(str) {
  let tag = "p";
  while (str.includes(`$${tag}$`)) tag += "p";
  return `$${tag}$${str}$${tag}$`;
}

// Postgres text[] literal, e.g. array['a','b'].
function pgArray(items) {
  if (!items?.length) return "'{}'";
  return `array[${items.map((s) => `'${String(s).replace(/'/g, "''")}'`).join(", ")}]`;
}

const rows = prompts.map((p) => {
  const cols = [
    dq(p.slug),
    dq(p.title),
    dq(p.description),
    dq(p.content),
    dq(p.category),
    pgArray(p.tags),
    pgArray(p.models),
    p.featured ? "true" : "false",
  ];
  return `  (${cols.join(", ")})`;
});

const sql = `-- AUTO-GENERATED by supabase/generate-seed.mjs — do not edit by hand.
-- Run after schema.sql to load the curated prompts. Idempotent (on conflict).

insert into public.prompts
  (slug, title, description, content, category, tags, models, featured)
values
${rows.join(",\n")}
on conflict (slug) do nothing;
`;

const out = join(here, "seed.sql");
writeFileSync(out, sql, "utf8");
console.log(`Wrote ${out} (${prompts.length} prompts).`);
