-- AI Prompt Hub — Supabase schema
--
-- Reference only: this build reads from the local seed (src/data/prompts.js).
-- Run this in the Supabase SQL editor when you're ready to move to the DB, then
-- flip the commented queries in src/lib/prompts.js to read from the table.
--
-- The column set matches the seed object shape 1:1.

create table if not exists public.prompts (
  id          bigint generated by default as identity primary key,
  slug        text not null unique,
  title       text not null,
  description text not null,
  content     text not null,
  category    text not null,
  tags        text[] not null default '{}',
  models      text[] not null default '{}',
  featured    boolean not null default false,
  created_at  timestamptz not null default now()
);

create index if not exists prompts_category_idx on public.prompts (category);
create index if not exists prompts_featured_idx on public.prompts (featured);

-- Row Level Security: prompts are public content, so allow anonymous SELECT only.
-- Writes are intentionally NOT granted to the anon role — inserts/updates should
-- go through a privileged server-side (service-role) path.
alter table public.prompts enable row level security;

drop policy if exists "Public read access" on public.prompts;
create policy "Public read access"
  on public.prompts
  for select
  to anon, authenticated
  using (true);

-- ── Seed data ───────────────────────────────────────────────────────────────
-- Mirror src/data/prompts.js. Keep the two in sync until the DB is the source
-- of truth, at which point the seed file can be deleted.
--
-- Example insert (repeat per prompt):
--
-- insert into public.prompts (slug, title, description, content, category, tags, models, featured)
-- values (
--   'blog-post-outline',
--   'SEO Blog Post Outline',
--   'Generate a structured, search-optimized blog outline for any topic.',
--   'You are an expert SEO content strategist...',
--   'writing',
--   array['blog','seo','content','outline','writing'],
--   array['ChatGPT','Claude'],
--   true
-- );
