-- AI Prompt Hub — Supabase schema
--
-- The site now reads/writes prompts from this table (see src/lib/prompts.js).
-- Run this whole file once in the Supabase SQL editor, then run supabase/seed.sql
-- to load the curated prompts. Generated prompts are inserted at runtime by the
-- /api/generate route using the anon key, governed by the RLS policy below.

create table if not exists public.prompts (
  id          bigint generated by default as identity primary key,
  slug        text not null unique,
  title       text not null,
  description text not null,
  content     text not null,
  category    text not null,
  tags        text[] not null default '{}',
  models      text[] not null default '{}',
  featured    boolean not null default false,
  -- 'curated' = hand-authored seed, 'generated' = created by the AI generator.
  source      text not null default 'curated',
  -- Deterministic hash of the normalized generator inputs. Lets us reuse an
  -- existing prompt instead of regenerating a duplicate. NULL for curated rows
  -- (Postgres allows multiple NULLs under a UNIQUE constraint).
  input_hash  text unique,
  created_at  timestamptz not null default now()
);

-- Idempotent upgrade path for tables created before source/input_hash existed.
alter table public.prompts
  add column if not exists source text not null default 'curated';
alter table public.prompts
  add column if not exists input_hash text;

create index if not exists prompts_category_idx on public.prompts (category);
create index if not exists prompts_featured_idx on public.prompts (featured);
create index if not exists prompts_created_at_idx on public.prompts (created_at desc);
-- UNIQUE on input_hash powers dedup (NULLs allowed for curated rows).
create unique index if not exists prompts_input_hash_key on public.prompts (input_hash);

-- ── Row Level Security ───────────────────────────────────────────────────────
alter table public.prompts enable row level security;

-- Anyone may read every prompt (public content).
drop policy if exists "Public read access" on public.prompts;
create policy "Public read access"
  on public.prompts
  for select
  to anon, authenticated
  using (true);

-- Anyone may INSERT, but only a well-formed *generated* prompt. This lets the
-- server route persist generations with the anon key without exposing the
-- ability to write curated rows or self-promote to featured. Curated rows must
-- be inserted from a privileged context (the SQL editor / service role).
drop policy if exists "Anon can insert generated prompts" on public.prompts;
create policy "Anon can insert generated prompts"
  on public.prompts
  for insert
  to anon, authenticated
  with check (
    source = 'generated'
    and featured = false
    and char_length(content) between 1 and 8000
    and char_length(title) between 1 and 200
    and input_hash is not null
  );

-- ── Realtime ─────────────────────────────────────────────────────────────────
-- Stream INSERT / UPDATE / DELETE on prompts to subscribed browsers so the
-- library and featured lists update live (see src/hooks/useRealtimePrompts.js).
-- Idempotent: only adds the table to the realtime publication if not already in.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'prompts'
  ) then
    alter publication supabase_realtime add table public.prompts;
  end if;
end $$;

-- DELETE events carry the primary key by default; FULL also exposes old values
-- of other columns, which keeps filtered live views (e.g. featured-only) correct.
alter table public.prompts replica identity full;

-- Seed the curated prompts by running supabase/seed.sql after this file.
