-- AUTO-GENERATED by supabase/generate-seed.mjs — do not edit by hand.
-- Run after schema.sql to load the curated prompts. Idempotent (on conflict).

insert into public.prompts
  (slug, title, description, content, category, tags, models, featured)
values
  ($p$blog-post-outline$p$, $p$SEO Blog Post Outline$p$, $p$Generate a structured, search-optimized blog outline for any topic.$p$, $p$You are an expert SEO content strategist. Create a detailed blog post outline for the topic: "[TOPIC]".

Include:
- An H1 title (under 60 characters, includes the primary keyword)
- A one-sentence meta description (under 155 characters)
- 5–7 H2 sections with 2–3 bullet points each
- A suggested list of 5 related long-tail keywords
- A short FAQ section (3 questions) targeting "People Also Ask"

Write in a clear, authoritative tone aimed at [AUDIENCE].$p$, $p$writing$p$, array['blog', 'seo', 'content', 'outline', 'writing'], array['ChatGPT', 'Claude'], true),
  ($p$code-reviewer$p$, $p$Senior Code Reviewer$p$, $p$Get a rigorous, actionable code review with severity-ranked findings.$p$, $p$You are a senior software engineer performing a thorough code review. Review the following code:

```
[PASTE CODE]
```

For each issue, provide:
1. Severity (Critical / High / Medium / Low)
2. The exact location (function or line)
3. Why it's a problem
4. A concrete fix (with a code snippet)

Cover correctness bugs, security, performance, and readability. End with the single highest-impact change to make first.$p$, $p$coding$p$, array['code review', 'engineering', 'bugs', 'refactor', 'coding'], array['Claude', 'ChatGPT'], true),
  ($p$cold-email-writer$p$, $p$High-Converting Cold Email$p$, $p$Write a concise, personalized cold outreach email that gets replies.$p$, $p$You are a B2B sales copywriter. Write a cold email to [PROSPECT ROLE] at [COMPANY].

Context about my product: [PRODUCT DESCRIPTION]
The specific pain point I solve: [PAIN POINT]

Rules:
- Under 120 words
- A personalized first line referencing [SPECIFIC DETAIL]
- One clear value proposition
- A single, low-friction call to action (a question, not a meeting demand)
- No buzzwords, no "I hope this email finds you well"

Provide 2 subject line options.$p$, $p$marketing$p$, array['email', 'sales', 'outreach', 'copywriting', 'marketing'], array['ChatGPT', 'Claude'], true),
  ($p$midjourney-product-shot$p$, $p$Midjourney Product Photography$p$, $p$Craft a detailed Midjourney prompt for a studio-quality product shot.$p$, $p$A professional studio product photograph of [PRODUCT], centered on a [SURFACE/BACKGROUND], soft diffused lighting from the left, subtle reflections, shallow depth of field, ultra-detailed, commercial advertising style, shot on a 85mm lens --ar 4:5 --style raw --v 6$p$, $p$image$p$, array['midjourney', 'image', 'product', 'photography', 'design'], array['Midjourney'], false),
  ($p$meeting-summarizer$p$, $p$Meeting Notes → Action Items$p$, $p$Turn messy meeting notes into a clean summary with owners and deadlines.$p$, $p$You are an executive assistant. Turn the following raw meeting notes into a structured summary:

[PASTE NOTES]

Output exactly these sections:
1. **TL;DR** — 2 sentences
2. **Key Decisions** — bulleted
3. **Action Items** — a table with columns: Task | Owner | Due Date
4. **Open Questions** — bulleted

If an owner or due date is unknown, write "TBD".$p$, $p$productivity$p$, array['meeting', 'summary', 'notes', 'action items', 'productivity'], array['ChatGPT', 'Claude'], true),
  ($p$business-plan-lean$p$, $p$Lean One-Page Business Plan$p$, $p$Draft a focused one-page business plan from a single idea sentence.$p$, $p$You are a startup advisor. Turn this idea into a one-page lean business plan:

Idea: [ONE SENTENCE IDEA]

Use the lean canvas structure:
- Problem
- Customer Segments
- Unique Value Proposition
- Solution
- Channels
- Revenue Streams
- Cost Structure
- Key Metrics
- Unfair Advantage

Keep each section to 2–3 bullet points. Be specific and realistic, not generic.$p$, $p$business$p$, array['startup', 'business plan', 'strategy', 'lean canvas', 'business'], array['ChatGPT', 'Claude'], false),
  ($p$explain-like-expert$p$, $p$Explain Anything, Two Levels$p$, $p$Explain any concept simply, then at an expert level — great for learning.$p$, $p$Explain the concept of "[CONCEPT]" twice:

1. **Like I'm 12** — a simple analogy anyone can grasp, no jargon.
2. **Like I'm an expert** — precise, technical, with the key terms and the one common misconception people get wrong.

End with a 3-item "What to learn next" list.$p$, $p$productivity$p$, array['learning', 'explain', 'education', 'teaching', 'productivity'], array['ChatGPT', 'Claude'], false),
  ($p$react-component-builder$p$, $p$Production React Component$p$, $p$Generate a clean, accessible React component to a precise spec.$p$, $p$You are a senior React engineer. Build a component to this spec:

Component: [NAME]
Props: [LIST PROPS + TYPES]
Behavior: [DESCRIBE BEHAVIOR]

Requirements:
- Functional component with hooks
- Accessible (proper ARIA, keyboard support)
- Tailwind CSS for styling
- Handle loading and empty states
- No external dependencies unless necessary

Return only the component code, then a 2-line usage example.$p$, $p$coding$p$, array['react', 'component', 'frontend', 'tailwind', 'coding'], array['Claude', 'ChatGPT'], false),
  ($p$twitter-thread$p$, $p$Viral Twitter/X Thread$p$, $p$Turn one idea into an engaging, well-structured X thread.$p$, $p$You are a social media ghostwriter. Write a Twitter/X thread about: [TOPIC].

Structure:
- Hook tweet (bold claim or surprising fact, under 200 chars)
- 5–8 body tweets, each one standalone-valuable
- A closing tweet with a soft CTA to follow/reply

Use short lines, no hashtags, and one concrete example or number per tweet. Number the tweets.$p$, $p$marketing$p$, array['twitter', 'x', 'thread', 'social media', 'marketing'], array['ChatGPT', 'Claude'], false),
  ($p$logo-concept$p$, $p$Minimalist Logo Concept$p$, $p$Generate a clean vector-style logo concept prompt for any brand.$p$, $p$Minimalist vector logo for "[BRAND NAME]", a [INDUSTRY] company. Simple geometric mark, [COLOR] on white background, flat design, negative space, memorable and scalable, no text, no gradients, centered --v 6 --style raw$p$, $p$image$p$, array['logo', 'branding', 'design', 'vector', 'midjourney'], array['Midjourney'], false),
  ($p$competitor-analysis$p$, $p$Competitor Analysis Matrix$p$, $p$Produce a structured competitor comparison for a market or product.$p$, $p$You are a market analyst. Build a competitor analysis for [MY PRODUCT/COMPANY] in the [MARKET] space.

Compare against these competitors: [LIST 3–5].

Output a markdown table with rows for: Pricing, Target Customer, Core Strength, Core Weakness, Key Differentiator.

Then write a short "Where we can win" paragraph identifying the clearest gap in the market.$p$, $p$business$p$, array['competitor', 'analysis', 'market research', 'strategy', 'business'], array['ChatGPT', 'Claude'], false),
  ($p$story-continuation$p$, $p$Fiction Co-Writer$p$, $p$Continue a story in a consistent voice with vivid, controlled pacing.$p$, $p$You are a fiction co-writer. Continue the following story, matching its tone, tense, and point of view exactly:

[PASTE STORY SO FAR]

Write the next [N] paragraphs. Advance the plot with one concrete new development, show don't tell, and end on a subtle hook. Do not summarize what came before.$p$, $p$writing$p$, array['fiction', 'story', 'creative writing', 'narrative', 'writing'], array['Claude', 'ChatGPT'], false)
on conflict (slug) do nothing;
